version: '3.7'
services:
  jenkins:
    image: 15625611d6fb
    stdin_open: true
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - '/var/jenkins_home:/var/jenkins_home'
      - '${HOME}/app:/var/jenkins_home/app'
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib64/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    tty: true
